### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by snow-jallen** [matusf/openapi-fuzzer#14]
I tried running 
`docker run --rm -it rust`

Then running
`cargo install openapi-fuzzer`

Then running 
`openapi-fuzzer --url http://localhost/swagger --spec http://localhost/swagger/v1/swagger.json`

But I just get back
`Error: No such file or directory (os error 2)`

...Not particularly helpful, but I'm not sure where to go from here.  As far as I can tell I'm doing what the docs said to do.

**Comment by matusf** [comment]
The `--spec` option takes a file as an argument not an url.

**Comment by snow-jallen** [comment]
Thank you, that did the trick.  I guess that just wasn't clear to me in the docs, I appreciate the clarification.

**Comment by matusf** [comment]
No problem. I'll try to improve the help message & docs.
