### ISSUE TITLE
Mention OpenAPI specification version in README

### ISSUE THREAD

**Issue by TheDutchMC** [matusf/openapi-fuzzer#15]
Hi,

Not much of an issue really, but it would be helpful I think. My webservers generate OpenAPI v2 specifications, which I tried feeding into this program, which didn't go too well. After some thinking I converted it to an OpenAPPI v3 spec, which did work.

It might be worth to mention the following in the README:
- OpenAPI v3 is required
- Whether JSON or YAML should be used, I only tried YAML thusfar

If wanted, I can open a PR for this.
Thanks!

**Comment by matusf** [comment]
Hi, thanks for the suggestion. It should be indeed mentioned which OpenAPI versions are supported. As for the JSON vs YAML, it loads YAML, but since YAML is a superset of JSON, JSON should be fine as well. I  agree, it would be more helpful, if it was mentioned explicitly in the readme.

**Comment by TheDutchMC** [comment]
I'll open up a PR adding the version. I'll try if JSON works out of the box, if it doesn't I'll add that too.
