### ISSUE TITLE
Allow multiple HTTP codes to be ignored

### ISSUE THREAD

**Issue by opsdisk** [matusf/openapi-fuzzer#16]
Currently, it looks like only one can be ignored per run

```none
$ ./openapi-fuzzer --spec spec.json -u http://127.0.0.1/ -i 403,404
Error parsing option '-i' with value '403,404': invalid digit found in string
```

**Comment by matusf** [comment]
Hi, it is possible to ignore multiple HTTP status codes. You need to pass several `-i` flags to the fuzzer. e.g. 
```
./openapi-fuzzer --spec spec.json -u http://127.0.0.1/ -i 403 -i 404
```

**Comment by opsdisk** [comment]
Appreciate the quick response @matusf I didn't think to try that.  Thanks for creating this tool!
