### ISSUE TITLE
Add a rate-limiting feature for APIs w/ rate-limits

### ISSUE THREAD

**Issue by jasikpark** [matusf/openapi-fuzzer#23]
I'm not sure how you'd do this - maybe I should just patch my api I'm fuzzing to not rate-limit, but I'm getting too many 429's atm

Would it be possible to configure a rate-limiting system for the fuzzer (hilarious, i know) so that I can avoid 429's?

**Comment by matusf** [comment]
For now, you can ignore the 429 codes with `-i 429`. I know it is not ideal. But at least it will not clutter your FS. However, it is a good feature, I'll try to implement it. But now I'm focusing on other parts of the fuzzer.
