### ISSUE TITLE
Error: unable to send request: Bad Header

### ISSUE THREAD

**Issue by hcrudolph** [matusf/openapi-fuzzer#30]
Hi there, first off, thanks a bunch for this great project!

When building the latest version from source and running it against the API under test, I get the following error:
```
METHOD  PATH                                           STATUS   MEAN (μs) STD.DEV. MIN (μs)   MAX (μs)
Error: unable to send request: Bad Header: invalid header 'Accept-Encoding: ùw𑐲ㅯȺ`%È🅓ￗ`C&K$ଲWব^𐳝$x"'hr<.¥'
```

Notably, this does not happen with the older v0.1.3 on crates.io

**Comment by matusf** [comment]
Hi, thanks for the report. Could you please attach a minimal version of the specification where this happens?

**Comment by hcrudolph** [comment]
The specification where I get the particular error above is this one: https://github.com/jdegre/5GC_APIs/blob/Rel-18/TS29510_Nnrf_NFDiscovery.yaml

Before testing, I've resolved all the external references and put the result through a linter to confirm its compliance.
