### ISSUE TITLE
Add official (docker) images

### ISSUE THREAD

**Issue by BreiteSeite** [matusf/openapi-fuzzer#9]
Hi,

first - thank you for the project. It looks really nice. I will try it out soon.

It would be nice if there would be some docker support so not everyone needs to build this themselves which in return lower the entry-barrier to test/use this.

In case i find the time i might gonna send a PR your way if you would be interested.

**Comment by matusf** [comment]
Hi, thanks for a suggestion. Yes, that is good idea. I'll try to add it soon, or feel free to send a PR, if you find the time.
